import _ from 'lodash';
import './style.scss';

import './images/loupe.svg';
import './images/check.svg';
import './images/view.svg';
import './images/review.svg';
import './images/arrow-left.svg';
import './images/logo.png';
import './images/photo_not.png';
import './images/photo_is.png';
import './images/meat_1.png';
import './images/meat_2.png';
import './images/meat_3.png';
import './images/meat_4.png';
import './images/meat_5.png';
import './images/meat_6.png';
import './images/meat_7.png';
import './images/meat_8.png';
import './images/meat_9.png';
import './images/meat_10.png';